# Generated by Django 5.2.8 on 2026-05-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_supplier_phone_supplier_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='breed',
            field=models.CharField(blank=True, help_text='Breed or type of eggs (e.g. Rhode Island Red, Broiler).', max_length=100),
        ),
        migrations.AddField(
            model_name='batch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatches', to='inventory.batch'),
        ),
    ]
