# Generated by Django 5.2.8 on 2026-05-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_batch_created_by_batch_updated_by_expense_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('equipment', 'Equipment'), ('feed', 'Feed'), ('labor', 'Labor'), ('medicine', 'Medicine'), ('phone', 'Phone'), ('supplies', 'Supplies'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
