# Generated by Django 5.2.15 on 2026-06-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_batch_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this expense is attributed to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier this expense is attributed to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='initial_quantity',
            field=models.PositiveIntegerField(help_text='Number of eggs or chicks at the time of purchase. Does not change.'),
        ),
    ]
