# Generated by Django 5.2.15 on 2026-06-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_expense_batch_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('electricity', 'Electricity'), ('equipment', 'Equipment'), ('feed', 'Feed'), ('labor', 'Labor'), ('maintenance', 'Maintenance'), ('medicine', 'Medicine'), ('packaging', 'Packaging'), ('phone', 'Phone'), ('supplies', 'Supplies'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
