# Generated by Django 5.2 on 2026-07-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='age_end_date',
            field=models.DateField(blank=True, help_text='Date when aging stopped (set when batch is marked GROWN). Age freezes at this point rather than continuing to increment.', null=True),
        ),
    ]
