# Generated by Django 5.2 on 2026-07-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_batch_age_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('customs_excise', 'Customs & Excise'), ('electricity', 'Electricity'), ('equipment', 'Equipment'), ('feed', 'Feed'), ('labor', 'Labor'), ('maintenance', 'Maintenance'), ('medicine', 'Medicine'), ('packaging', 'Packaging'), ('phone', 'Phone'), ('service_charges', 'Service Charges'), ('supplies', 'Supplies'), ('transport', 'Transport'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
