# Generated by Django 5.2 on 2026-05-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
