# Generated by Django 5.2.8 on 2026-05-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_1',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_1_type',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('personal', 'Personal'), ('mobile', 'Mobile'), ('fax', 'Fax'), ('other', 'Other')], default='mobile', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_1_whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_2_type',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('personal', 'Personal'), ('mobile', 'Mobile'), ('fax', 'Fax'), ('other', 'Other')], default='mobile', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_2_whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_3',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone 3'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_3_type',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('personal', 'Personal'), ('mobile', 'Mobile'), ('fax', 'Fax'), ('other', 'Other')], default='mobile', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_3_whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp'),
        ),
    ]
