# Generated by Django 5.2.8 on 2026-05-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batch_breed_batch_notes_alter_hatch_batch'),
        ('sales', '0003_remove_customer_phone_customer_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_lines', to='inventory.batch'),
        ),
    ]
