# Generated by Django 5.2 on 2026-07-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_meat_sale_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('death', 'Death'), ('donation', 'Donation'), ('personal_use', 'Personal Use')], default='death', help_text='Category of inventory adjustment.', max_length=20),
        ),
    ]
