# Generated by Django 5.2 on 2026-08-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_finalized_status_payment_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], default='', help_text='How the customer paid (recorded when the sale is finalized or closed).', max_length=16),
        ),
    ]
