# Generated by Django 5.2 on 2026-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('bank_deposit', 'Bank Deposit')], default='', help_text='How the customer paid (recorded when the sale is finalized or closed).', max_length=16),
        ),
    ]
