# Generated by Django 5.2 on 2026-08-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('death', 'Death'), ('donation', 'Donation'), ('personal_use', 'Personal Use'), ('damaged', 'Damaged')], default='death', help_text='Category of inventory adjustment.', max_length=20),
        ),
    ]
